version: '3'

services:
    codebox_web:
        build:
            context: .
            dockerfile: ./server/Dockerfile
        volumes:
            - ~/Desktop/MOCKCOMP:/comp
            - ./web/static:/app/web/static
            - /tmp:/tmp
        ports:
            - 8080:80
        networks:
            - internet

    codebox_executer:
        build:
            context: .
            dockerfile: ./executer/Dockerfile
        restart: always
        networks:
            - no-internet
        volumes:
            - ~/Desktop/MOCKCOMP:/comp
            - /tmp:/tmp

networks:
    no-internet:
        driver: overlay
        internal: true
    internet:
        driver: bridge
